# Generated by Django 4.0.6 on 2022-08-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_4', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(default=1111111111111111111111111111),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
