# Generated by Django 4.0.6 on 2022-08-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=30)),
                ('way', models.TextField()),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_3.mode')),
            ],
            options={
                'verbose_name': '标题',
                'verbose_name_plural': '标题',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=60)),
                ('way', models.CharField(max_length=60)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_3.title')),
            ],
        ),
    ]
