# Generated by Django 4.0.6 on 2022-08-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '内容', 'verbose_name_plural': '内容'},
        ),
        migrations.AddField(
            model_name='mode',
            name='brief',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
