# Generated by Django 4.0.6 on 2022-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3', '0004_alter_content_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
