# Generated by Django 4.0.4 on 2022-07-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='kind',
            field=models.CharField(blank=True, default='没有联系方式', max_length=10, null=True),
        ),
    ]
