# Generated by Django 4.0.4 on 2022-07-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_feedback_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(default='没有联系方式', max_length=35, null=True),
        ),
    ]
