# Generated by Django 4.0.4 on 2022-07-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_feedback_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
